// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SmokeQuit.Repositories.DuongLNT.Models;

public partial class LeaderboardsDuongLnt
{
    public int LeaderboardsDuongLntid { get; set; }

	[Required(ErrorMessage = "User Id không được để trống.")]
	public int UserId { get; set; }

    public int? PlanId { get; set; }

	[Range(0, int.MaxValue, ErrorMessage = "Ngày không hút thuốc không được âm")]
	public int? DaySmokeFree { get; set; }

	[Range(0, double.MaxValue, ErrorMessage = "Tiền lưu trữ không được âm")]
	public double? MoneySave { get; set; }

	[Range(1, int.MaxValue, ErrorMessage = "Xếp hạng vị trí phải lớn hơn 1")]
	public int? RankPosition { get; set; }

	[Range(0, int.MaxValue, ErrorMessage = "Tổng số thành tích không được âm")]
	public int? TotalAchievements { get; set; }

	[Range(0, double.MaxValue, ErrorMessage = "Điểm tiến bộ không được âm")]
	public double? ProgressScore { get; set; }

	[StringLength(255, ErrorMessage = "Ghi chú không được vượt quá 255 ký tự.")]
    public string Note { get; set; }

	[Range(0, int.MaxValue, ErrorMessage = "Chuỗi đếm không được âm.")]
	public int? StreakCount { get; set; }

	[Range(0, int.MaxValue, ErrorMessage = "Đóng góp của cộng đồng không được âm.")]
	public int? CommunityContribution { get; set; }

    public bool IsTopRanked { get; set; }

    public DateTime? LastUpdate { get; set; }

    public DateTime? CreatedTime { get; set; }

    public virtual QuitPlansAnhDtn Plan { get; set; }

    public virtual SystemUserAccount User { get; set; }
}